
package fr.afcepf.al30.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceTva", targetNamespace = "http://service.ws.al30.afcepf.fr/")

public interface IServiceTva {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuteur", targetNamespace = "http://service.ws.al30.afcepf.fr/", className = "fr.afcepf.al30.ws.service.GetAuteur")
    @ResponseWrapper(localName = "getAuteurResponse", targetNamespace = "http://service.ws.al30.afcepf.fr/", className = "fr.afcepf.al30.ws.service.GetAuteurResponse")
    @Action(input = "http://service.ws.al30.afcepf.fr/IServiceTva/getAuteurRequest", output = "http://service.ws.al30.afcepf.fr/IServiceTva/getAuteurResponse")
    public String getAuteur();

    /**
     * 
     * @param taux
     * @param ht
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tva", targetNamespace = "http://service.ws.al30.afcepf.fr/", className = "fr.afcepf.al30.ws.service.Tva")
    @ResponseWrapper(localName = "tvaResponse", targetNamespace = "http://service.ws.al30.afcepf.fr/", className = "fr.afcepf.al30.ws.service.TvaResponse")
    @Action(input = "http://service.ws.al30.afcepf.fr/IServiceTva/tvaRequest", output = "http://service.ws.al30.afcepf.fr/IServiceTva/tvaResponse")
    public double tva(
        @WebParam(name = "ht", targetNamespace = "")
        double ht,
        @WebParam(name = "taux", targetNamespace = "")
        double taux);

}
